import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navigation from "../Components/Navigation";
//relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32
//mt-10 sm:mt-12 md:mt-16 lg:mt-20 xl:mt-28
import Hero from "../Components/Hero";
import Content from "../Components/Content";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main>
        <Hero
          title={[
            {
              text: "Xen's Yu-Gi-Oh! ",
            },
            {
              text: "Speed Duel ",
              classes: "text-teal-500",
            },
            {
              text: "Library",
            },
          ]}
          subtext="A quick lookup of Yu-Gi-Oh speed duel decks to get playing quickly!"
        />

        <Content
          heading="Fast & Classic Way to Duel!"
          subtext={[
            {
              text: "The latest Speed-Duels products have been collected to give the ",
            },
            {
              text: "duelist a wide viarity of options.",
              classes: "underline decoration-teal-500",
            },
            {
              text: " This websites goal is to help duelist pick up a",
            },
            {
              text: "uniuqe pre-built deck",
              classes: "underline decoration-teal-500",
            },
            {
              text: " and get right into the action.",
            },
          ]}
          reverse
        />
      </main>
    </>
  );
};

export default Home;
